.TH ELECTRO 1
.SH NAME
.RS
electro_1.0-1 \ - Calculate replacement resistance.
.RE
.RE
.SH SYNOPSIS
.RS
electro [OPTION]...
.RE
.RE
.RS
.RS
.SH DESCRIPTION
.RS
The program asks for voltage source, connection method, number of components and the value of each component and returns the resulting resistance with one decimal, power development with two decimals and replacement resistances from the E12 series. 
.RE
.RE
.SH OPTIONS
.RS
In the current version of 'electro' there are no available options.
.RE
.RE
.SH BUGS
.RS
This program has been debugged with Lintian. Should you discover a bug please report this to devs@electroteam.com so it can be investigated. 
.RE
.RE
.SH AUTHOR
.RS
Zacharias Wesén
